version: '2'
services:
  samba4:
    container_name: samba4
    image: iamgavinj/samba4
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    networks:
      macvlan:
        ipv4_address: 10.1.0.9
    hostname: nas.corp.scurr.me
    volumes:
      - /zdata/Media:/Media
      - ${PWD}/smb.conf:/opt/etc/smb.conf

networks:
  macvlan:
    external: true
